### ISSUE TITLE
All the text field content is deleted with just one tap

### ISSUE THREAD

**Issue by gabriela-pinheiro** [siqwin/mask_text_input_formatter#10]
all the text is deleted with just one tap "delete" button, not one character by one

**Comment by softronaut** [comment]
Did you figured out how to solve this? I'm having same issue and couldn't find reason or solution.

**Comment by AlexHartford** [comment]
Can this be reopened?  Also facing this issue.

**Comment by AlexHartford** [comment]
**I got it working by lifting up the MaskTextInputFormatter to the parent of the child widget I am using and passing it as a parameter to the child.**  Give this a shot!!

This prevents it from being reconstructed which is why the content of the text field is cleared.  Also, make sure you declare it outside of the build method.  This might not be a problem if you are using a stateless widget but I am using hooks in my project and this is what I found to be the simplest solution.

**Comment by softronaut** [comment]
@AlexHartford I think it's related to the #19 . If @siqwin accepts the pull request, it will be solved.

**Comment by Andreigr0** [comment]
Still happens. I mean it deletes full `TextField`'s text with one tap on delete button. 
Also on Android delete button deletes 2 symbols while on iOS it deletes, as it should, 1 symbol

**Comment by fhsbatista** [comment]
I'm facing the same problem :/ And I have already tried to instantiate my inputformmatter on my State class, but the problem still occurs.

**Comment by Andreigr0** [comment]
@fhsbatista consider using this package. It's much better than this https://pub.dev/packages/flutter_multi_formatter

**Comment by fhsbatista** [comment]
The problem was occuring when I set a text to the controller that was beeing attached to the text field. I could solve the error by setting the text (that one I was setting on the controller) on the "initialText" parameter of the MaskTextInputFormatter.

**Comment by khloukrada** [comment]
> The problem was occuring when I set a text to the controller that was beeing attached to the text field. I could solve the error by setting the text (that one I was setting on the controller) on the "initialText" parameter of the MaskTextInputFormatter.

Thank you. This fixes the issue.
